### ISSUE TITLE
Fail in building simavr

### ISSUE THREAD

**Issue by tclin914** [dylanmckay/simavr-sys#5]
Hi,

I tried to follow the command in README. But I got a failure.

$ cargo run --bin avr-lit -- --avr-gcc
Compiling simavr-sys v1.5.8                                                                                                                                              error: failed to run custom build command for `simavr-sys v1.5.8`                                                                                                           process didn't exit successfully: `/home/users/jim/avr/avr-compiler-integration-tests/target/debug/build/simavr-sys-ed274afab149c4ed/build-script-build` (exit code: 101)   --- stderr                                                                                                                                                                  ./simavr/simavr/sim/sim_avr.h:446:10: fatal error: 'stdarg.h' file not found                                                                                                ./simavr/simavr/sim/sim_avr.h:446:10: fatal error: 'stdarg.h' file not found, err: true                                                                                     thread 'main' panicked at 'could not generate bindings: ()', libcore/result.rs:1009:5                                                                                       note: Run with `RUST_BACKTRACE=1` for a backtrace.

I'm not familiar with Rust or Cargo. Could you give me some suggestions. 
Thanks.

**Comment by dylanmckay** [comment]
Hey @tclin914,

Can you compile [simavr](https://github.com/buserror/simavr) from source the regular way, using `make`?

It is interesting that it cannot find `stdarg.h`. Do you have a full C/C++ compiler on your system?

**Comment by tclin914** [comment]
Hi @dylanmckay,

It looks like the issue is my environment.

I use docker instead of native environment is well.

Thank you for your help.
